### ISSUE TITLE
Generate Update SQL from Entity

### ISSUE THREAD

**Issue by bajajyog** [liefke/org.fastnate#17]
Please advise, how to generated Update SQL from Entity.  In your github code, there is update statement which can generate update sql. I find way to generate insert sql from entity as:-
StringWriter result = new StringWriter();
Notes notes = new Notes();
notes.setNote("123");
notes.setNoteOid("noteOid");
EntitySqlGenerator sqlGenerator = new EntitySqlGenerator(result);
sqlGenerator.write(notes);
			
System.out.println( result.toString());

**Comment by liefke** [comment]
I'm sorry, but I can't see any issue here. What is you question?

**Comment by bajajyog** [comment]
my question, is how to generate the update sql statement from Entity?. 
Fastnate provides api to generate insert sql statement from entity.
Let me know if you need more info.

**Comment by liefke** [comment]
Ah - you mean you want to to update an existing entity with Fastnate?

I'm sorry, but this is not possible at the moment. Fastnate is intended to import new entities (it works best when importing into an empty database). The `UpdateStatement` is used internally to push any additional updates that are needed during the import of such new entities, for example when two inserted entities reference each other.

But if you describe what you want to do in detail, maybe I could help you or add such functionality to Fastnate. I've already thought about simple updates like 

    Notes notes = sqlGenerator.find(Notes.class, id);
    notes.setNote("123");
    sqlGenerator.write(notes);

This would be easy to implement. The main problem is how to describe the reference to the existing entity. By id is the one which would work right away, but in most cases you don't know the id when you are "offline" and this is where the tricky part will start...

**Comment by liefke** [comment]
As you didn't describe your problem any further, I guess that it is not that important. I've created an enhancement issue for updates in #19 - you can track that one if you like.
