### ISSUE TITLE
Generated relative IDs are wrong

### ISSUE THREAD

**Issue by apenski** [liefke/org.fastnate#18]
results in unique key constraint exception when running a combined script

**Comment by liefke** [comment]
Can you tell me, wich generator and allocation size you use?

**Comment by apenski** [comment]
I use the table based id generator, with default value for the allocation size

**Comment by liefke** [comment]
The interpretation of the `TableGenerator` value column content varied between relative IDs and absolute IDs. It fixed it, it is now always the same interpretation: The content is (at least) the maximum allocated value + allocation size.
