### ISSUE TITLE
Fastnate should automatically determine dialect from DataSource

### ISSUE THREAD

**Issue by rjlasko** [liefke/org.fastnate#27]
I am currently using Fastnate in tandem with SpringBoot + Flyway, to preload data into certain tables when creating/upgrading new databases.  One major hurdle that I needed to clear was to have Fastnate automatically infer the correct dialect when the application properties changed the vendor of the database.  (ie. Local dev mode uses H2 whereas production deployment uses Oracle.)  The SpringBoot - Flyway bootstrapping mechanism does not provide access to the various beans that I might be able to specify the dialect with, as Flyway's Java migrations only allow the execution of SQL (adhering to the vendor dialect) via a provided `DataSource`.  This is the same issue that Fastnate presents.

A solution could infer the SQL dialect from the `DataSource`, which is possible, as shown here:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L204

I know that `JdbcUtils` is a Spring class, so perhaps this isn't as cut and dry.  However, slightly modifying that code, I was able to extract the `DatabaseDriver` type from the `DataSource`, and then implement a switch-case statement to match up the proper Fastnate SQL `GeneratorDialect` class to the determined `DatabaseDriver`.

**Comment by liefke** [comment]
There is already something similar in the [HibernateProvider](https://github.com/liefke/org.fastnate/blob/master/fastnate-generator/src/main/java/org/fastnate/generator/provider/HibernateProvider.java#L44). I could make these functions more accessible, but I'm not really sure if this will help you.

**Comment by rjlasko** [comment]
Thanks for the follow-up

This looks similar to what I had done, however I haven't been able to find a way to get access to the properties hiding in the spring context, when spring invokes the Flyway-scanned-class methods of mine...

**Comment by liefke** [comment]
I close this as I don't know how to provide further support here.
