### ISSUE TITLE
Skip synthetic fields

### ISSUE THREAD

**Issue by mathieu-lavigne** [liefke/org.fastnate#28]
In the generator the method AccessStyle.*.getDeclaredAttributes(Class<E>) should not grab synthetic fields/getters.

**Comment by liefke** [comment]
Thank you for your pull request - I merged it into 1.3.0. 

I adapted the changes for the master as well, but as you've already mentioned in your comment: both access types should ignore synthetics. Your pull request only includes a patch for `AccessStyle.METHOD` so I fixed it for `AccessStyle.FIELD` as well. 

There is currently no schedule for an 1.3.1. If you plan to use a bundle from central, you will have to wait until 1.4.0 is out in the next weeks.
