### ISSUE TITLE
Parent child relationship with preassigned ids -> Referential Integrity Error

### ISSUE THREAD

**Issue by OHDMax** [liefke/org.fastnate#30]
When a parent in a parent-child relationship has assigned a manual ID (the ID is not generated) and a child references such a parent, the generated SQL may result in a "Referential Integrity Error". This is because the SQL insert statement of the child references the parent before the insert statement for the parent is written.

Version: 1.4.0-SNAPSHOT (the buildNumber is 6)

**Comment by liefke** [comment]
Thank you for reporting this.

It is fixed now: The insert statement of the child is written without the parent id, which is updated with the help of an extra statement as soon as the insert of the parent is written.

**Comment by OHDMax** [comment]
I can confirm, this fixed my issue. Thanks for your fast bugfix!
