### ISSUE TITLE
Cannot instantiate the type EntitySqlGenerator

### ISSUE THREAD

**Issue by abhiramikl** [liefke/org.fastnate#31]
EntitySqlGenerator e = new EntitySqlGenerator(this.context);
e.write(courseEntity);
When creating an object of EntitySqlGenerator this error comes

"Cannot instantiate the type EntitySqlGenerator"

How can I solve it?

**Comment by liefke** [comment]
What the Java compiler is trying to say: There is no `EntitySqlGenerator` constructor with just the context. The generator needs _always_ a `Writer` as parameter, which is used as target of the generated statements.

**Comment by abhiramikl** [comment]
How will I initialize Writer, I tried but giving some error.

**Comment by liefke** [comment]
It depends on your purpose: Where do you want to write the SQL statements? To a file or to a string? Either use a `FileWriter` or a `StringWriter`.

**Comment by abhiramikl** [comment]
I need insert query of an entity class in a string.

**Comment by liefke** [comment]
The `EntitySqlGenerator` is not for generating queries, it is for generating insert statements. That having said, here is an example how you could do that:

    StringWriter writer = new StringWriter();
    EntitySqlGenerator generator = new WriterEntitySqlGenerator(writer, context);
    generator.write(myEntity);
    String sql = writer.toString();

This example is for Fastnate 1.3 - in the upcoming version 1.4 the class structure has changed a little bit - but the concept is the same.

**Comment by abhiramikl** [comment]
Hallo,
 Still same issue occurs when i try this code also.Code is given below:
      StringWriter writer = new StringWriter();
      EntitySqlGenerator e = new EntitySqlGenerator(writer , this.context);
      e.write(courseRecords);

**Comment by liefke** [comment]
You have to use a `WriterEntitySqlGenerator` in Fastnate 1.3.

**Comment by abhiramikl** [comment]
I'm using fastnate1.3.0, when calling WriterEntitySqlGenerator this error is throwing : 

nested exception is java.lang.UnsupportedClassVersionError: org/fastnate/generator/WriterEntitySqlGenerator : Unsupported major.minor version 52.0 (unable to load class org.fastnate.generator.WriterEntitySqlGenerator)] with root cause
java.lang.UnsupportedClassVersionError: org/fastnate/generator/WriterEntitySqlGenerator : Unsupported major.minor version 52.0 (unable to load class org.fastnate.generator.WriterEntitySqlGenerator)

**Comment by liefke** [comment]
It seems that you are developing or testing with Java 7. As Fastnate 1.3.0 was compiled with Java 8, you will have to switch to either Java 8 or Java 9.

**Comment by abhiramikl** [comment]
Hai,
 Fastnate1.2 also doesn't support with Java 7. My development environment
works only in java 7. Can u suggest which version will support with Java
7.  My requirement is I need insert query if an entity class. Please help
me.

**Comment by liefke** [comment]
As you can see [here](https://fastnate.org/#versions), the last version that supported Java 1.7 was 1.0.0-RC1. But that version was never published to Maven-Central. It is still available from our binary repository, which you can access as defined in our [download section](https://fastnate.org/#download) (look for snapshot builds).

As the _RC1_ indicates, that version had still some bugs - I hope you can use it nevertheless.
