### ISSUE TITLE
Support AttributeConverter

### ISSUE THREAD

**Issue by AlexanderHofmeister** [liefke/org.fastnate#36]
Fastnate does not support the following attribute:

	@Column(columnDefinition = "VARCHAR")
	@Convert(converter = StringListConverter.class)
	private List<String> strings = new ArrayList<>(); 

With StringListConverter like:

    @Converter
    public class StringListConverter implements AttributeConverter<List<String>, String> {

	    public String convertToDatabaseColumn(final List<String> list) {
	  	return String.join(",", list);
	    }

	    public List<String> convertToEntityAttribute(final String joined) {
	      	return new ArrayList<>(Arrays.asList(joined.split(",")));
	    }

    }

**Comment by liefke** [comment]
Fastnate supports now a converter defined at the property level (like in your example). It still doesn't supports global converters (as it doesn't scan all files). Maybe this is something for a later version.
