### ISSUE TITLE
Fastnate generating table even if Hibernate does not.

### ISSUE THREAD

**Issue by AlexanderHofmeister** [liefke/org.fastnate#44]
I have following entity

    @Entity
    public class KeyValue {

        @Id
        private Long id;
          
        public String key;
        public String value;

}

The entity is not creating because `key` is a reserved keyword. Fastnate on the other hand is  generating this line for importing via CSV file: 

`INSERT INTO UserSettings (id, key, user_id, value) VALUES (2, 'mykey', 1, 'myvalue');`

I am not sure whether it is the correct behaviour or not.

**Comment by liefke** [comment]
I didn't know that `key` is a reserved keyword for JPA. I even have some applications which declare such an attribute without any problem. Maybe it is only a keyword for your database? In that case Hibernate should have problems as well when accessing that attribute.

Could you review the issue title and example - I've got the feeling that they don't match the specified result?

**Comment by liefke** [comment]
Closed as no further action needed.
