### ISSUE TITLE
Attribute name bug on mapped property

### ISSUE THREAD

**Issue by feo81** [liefke/org.fastnate#45]
I have a Collection property on my entity with annotation @OneToMany(..., mappedBy = "incomDistrScheme", ...)
Using EntitySqlGenerator (verson 1.4.0) drops exception: org.fastnate.generator.context.ModelException: Unsupported "mapped by" property for public java.util.Collection ...
By debugging i see, that in line 679 of PluralProperty class calling of "entityClass.getProperties().get(this.mappedBy)" returns null 
Cause of entityClass.getProperties() collection do not have property "incomDistrScheme", but it have property "incomDtrScheme"
I guess, that error is in line 164 of AccessStyle class:
this.name = Introspector.decapitalize(getter.getName().replaceAll("^get|is", ""));
You don't have to use replaceAll() here. You need to use replaceFirst().

**Comment by liefke** [comment]
Thank you for your report and the clear analysis. 

I have to admit hat I usually use AccessStyle.FIELD in my projects.

Do you need a bugfix release or is a SNAPSHOT enough?

**Comment by feo81** [comment]
Bugfix release is better for me

**Comment by liefke** [comment]
I created version 1.4.1 which includes the fix of this and two other bugs.
May take one day until it is available in maven central.
