### ISSUE TITLE
Support Embeddable in Collection of Embeddables

### ISSUE THREAD

**Issue by propertius** [liefke/org.fastnate#54]
Given a collection of As (of type Embeddable), which also contains an Embeddable B in its definition, it would be desirable for the Fastnate to produce proper insert statements.

Mapping example:

    @OrderColumn
    @ElementCollection
    @AttributeOverrides({ 
        @AttributeOverride(name = "value.valueDE", column = @Column(name = "valueOverridenFromA1", nullable = false)),
        @AttributeOverride(name = "value.valueEN", column = @Column(name = "valueOverridenFromA2")) 
    })
    private final List<A> values;

    @Embeddable
    public class A {

        @Embedded
        @AttributeOverrides({
            @AttributeOverride(name = "valueDE", column = @Column(name = "valueOverriden1", nullable = false)),
            @AttributeOverride(name = "valueEN", column = @Column(name = "valueOverriden2")) 
        })
        private B value;

    @Embeddable
    public class B {

        private String valueDE;

        private String valueEN;

    }

**Comment by liefke** [comment]
Thank you for reporting this issue. 

I created a fix for the next release (1.6.0).

If you need a version which includes that fix, you can use our snapshot builds.
