### ISSUE TITLE
[Question] Is there anyway to do it using gradle instead?

### ISSUE THREAD

**Issue by hilmialf** [liefke/org.fastnate#57]
Hello liefke.. thanks for your interesting project here. I am just wondering if there is any way/guide to generate the data.sql using gradle instead of maven? I just happened to start a springboot using gradle and would be nice if fastnate provide a way to use it too. Looking forward to hearing from you.

**Comment by liefke** [comment]
Sorry, for the late response, somehow lost track of this one.

Sure it is possible, as you can call any java program from Gradle. But I guess you are interested in a Gradle plugin, which I currently can't provide.
