### ISSUE TITLE
JPA support?

### ISSUE THREAD

**Issue by pprabhu3430** [liefke/org.fastnate#8]
I noticed the fastnate code relies on the @MapsId annotation to present when creating onetoone and manytomany relationships. JPA i think does not use this, instead only hibernate uses this. 

Is there a work around for this for JPA entities. When my entities have something like this, 
@OneToMany(fetch = FetchType.LAZY)
	@JoinColumns({
				@JoinColumn(name = "Field_ID", referencedColumnName = "Field_ID", insertable=false , updatable=false),
				@JoinColumn(name = "Customer_ID", referencedColumnName = "Customer_ID", insertable=false , updatable=false) })

it fails with a ModelException - misses MapId for a singular property

**Comment by liefke** [comment]
`@MapsId` is nothing Hibernate specific - it is a common feature of JPA.

Fastnate only supports entities with a single primary key attribute, as it is difficult to build the SQL for references to entities with more than one primary key. We've already put that on our wishlist for version 2.0 (see #2). But as we are using Fastnate for projects where we can define our own database model with single ID attributes, it has only low priority for now.

**Comment by liefke** [comment]
You can find a list of supported JPA features on the [FAQ page](/liefke/org.fastnate/wiki/FAQ#which-jpa-features-are-supported) now.
